### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by joecryptotoo**

### CODE REVIEW

**Comment by andimarafioti** [comment]
Very nice 👌🏽 how can we test this ? Also can you add a section to the readme explaining how to use it? Thanks 🙏

**Comment by joecryptotoo** [comment]
> Very nice 👌🏽 how can we test this ? Also can you add a section to the readme explaining how to use it? Thanks 🙏

I added some guidance to the readme.

**Review by andimarafioti — APPROVED** [review]
Awesome work! Thank you

**Comment by itamargero** [comment]
Thanks!

**Pull request merged**
